import type { Metadata } from "next";
import { Questrial } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const questrial = Questrial({ weight: ["400"], subsets: ["latin"] });

const denton = localFont({
  src: [
    {
      path: "../public/fonts/bold700.otf",
      weight: "700",
    },
    {
      path: "../public/fonts/light300.otf",
      weight: "300",
    },
  ],
  variable: "--font-denton",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${questrial.className} ${denton.variable} bg-black`}>{children}</body>
    </html>
  );
}
